def json_data(jsonobject, i, column) :
    """
    Given a json object generated by NanoQt, it extracts the column of a the data nbr i
    """
    try :
        data_temp = jsonobject["measures"][i]["data"]
    except :
        print "Problem using data_json function"

    if type(column) == str:
        try :
            column = getposcolumn(data_temp, column)
        except :
            print "There is not such a column name, taking column = 1"
            column = 1
    temp = []

    for j in range(len(data_temp)):
        temp.append(data_temp[j][column-1])

    return temp
